### ISSUE TITLE
CLIP pre-trained model

### ISSUE THREAD

**Issue by zqyJason** [OliverRensu/DeepMIM#3]
Would you mind providing the CLIP pre-training model? The model provided by the official repository seems to be incompatible with your code.

**Comment by OliverRensu** [comment]
model, preprocess = clip.load("ViT-B/16", device=device)
torch.save(model.state_dict(), "xx.pth")

--clip_path xx.pth

**Comment by zqyJason** [comment]
Thank you!

**Comment by zqyJason** [comment]
> model, preprocess = clip.load("ViT-B/16", device=device) torch.save(model.state_dict(), "xx.pth")
> 
> --clip_path xx.pth

Thank you!
